### PR TITLE
update SAW recommendation

### PR DESCRIPTION
**Pull request by redfarg**
An extensive update (or more accurately, a first version with actual content) for the SAW recommendation, with formats in relevant domains and an info block for English/German.

### CODE REVIEW

**Comment by margaretha** [comment]
Dear Felix, 
thank you very much for your contribution. I have merged the file to the master branch and uploaded it to the production server. So it is now accessible at https://clarin.ids-mannheim.de/standards/views/view-centre.xq?id=SAW

Could you please check if it is alright?

I added your name as the curator. I hope it is okay. 

There is a missing format description LMV for domain Lexical Resource. Could it be that LMF is meant instead?

**Comment by bansp** [comment]
Dear Felix, 
Thanks from me as well! 

It's a small fix, please don't bother with a PR, but do tell: which LMF? The original standard-particular format, or the new one, defined as a customisation of the TEI?

(I'll see if I can change this conversation into an issue, so that we don't lose track of it)

**Comment by margaretha** [comment]
Hi Felix,
thanks for checking. I have updated the reference to the LMF page:
https://clarin.ids-mannheim.de/standards/views/view-format.xq?id=fLMF

that refers to ISO 24613-4:2021 (the new version). As Piotr mentioned, there is also the original format ISO 24613:2008. Since we probably will have two separate pages for each version, could you please clarify which version is recommended by SAW?

**Comment by redfarg** [comment]
Thank you for the update! 

The new version is perfect, thanks for checking!

**Pull request merged**
