### PR TITLE
add formats that exists in SIS and is currently in use at clarino repo

### PR DESCRIPTION
**Pull request by OyvindLGjesdal**
Work in progress, current list is based on file formats currently used with some exceptions missing definitions in SIS.

### CODE REVIEW

**Comment by bansp** [comment]
Thanks! :-) Quick question: by "Tiger", do you mean the original Mengel & Lezius 2000 format or the ISO SynAF part 2, which I think has been called "Tiger 2", at least by the Annis team?

**Comment by OyvindLGjesdal** [comment]
We are a bit unsure on why Tiger is on the CLARINO SIS page, but we guessed that someone had added it already, after browsing/evaluating our repo. Thus I'm a bit unsure on what the answer to your question is. I didn't notice any of either format, when going through the bitstreams in the repository, but we will figure it out report back.

**Comment by bansp** [comment]
I have just looked at the stage when we worked with a spreadsheet, a few years ago. In that spreadsheet, no responsible person is listed for CLARINO, and no recommendations are marked. (The "responsible person" would have been just one of the members of the Standards Committee; we had no one from Norway on the committee then, and apparently no one else volunteered; Hanna Hedeland **might** have contacted the centre, because she had attempted to contact all centres, but there's no guarantee that a trace of that remains anywhere.)

**Comment by bansp** [comment]
Hanna's note from back then says that CLARINO used the D-SPACE FAQ by the Lindat colleagues and a pointer to the old LRT document (neither of which being really very helpful for the task at hand).

It might be fair to assume that the previous CLARINO recommendations in the SIS may have been just a seed waiting for the centre to look at and want to correct. (So it's super to see you work on that! :-))

**Comment by bansp** [comment]
Tried to get back to the bottom of the blame stack and succeeded to the point where it looks like the Tiger recommendation was the only one present from nearly the very beginning, most likely just a filler. In other words, I'd suggest that you do not allocate time for researching this, and it should be safe to ignore that recommendation if you haven't by now found any evidence for it.

**Comment by bansp** [comment]
Just a note: it's OK to start small -- anything added to the recommendations of CLARINO now is an improvement, and can always be adjusted later.

My quasi-reviewer comment is that "XML" and "TEI" are extremely general, and both are toolkits for creating formats rather than formats themselves -- but, if it works for now, then why not, at least for the beginning.

I think the trick part is that publishing recommendations means a sort of a contract (naturally, one without big consequences other than a bit of a headache or a potential acidic exchange, maaaybe): if you say, "we recommend XML" then the depositing user can legitimately send any XML your way (maybe even including zipped XML called ".odt"), and expect that you take it as-is, or at least expect that all the processing is going to take place centre-side. And that may be OK for the centre, so this here is just a remark shared in good faith, hoping to perhaps help along :-)

**Comment by OyvindLGjesdal** [comment]
Thank you for your comments and I agree with them. The formats so far are limited to what I found in the repositorum and what we have deposited. My colleague will chime on formats accepted for ingestion into tools, but I think we have a large acceptance of formats also for that.

We want to post some more specific variants (of TEI in this case) not currently present, E.G. the Menota specification.

https://menota.org/HB3_D_schemas.xml

**Comment by bansp** [comment]
Great, we'll get an info file for the Menota format, thanks for sharing! 
Realistically, since this is a week of yet another long weekend, we may be able to put the recommendations online some time next week (but no pressure).

If you manage to submit something (or simply remove the draft flag from this PR) before June 4th, I am going to add it to the [next release of the recommendations](https://github.com/clarin-eric/standards/milestone/5), but, again, this is not meant to pressure you, and I am not at all sure if I can keep the date of the 4th. And if not in this release, then in the next. We are quasi-committed to do two format releases per year, but that's actually conditioned on whether there exists something sizable to be put into a release.

**Comment by bansp** [comment]
Thanks a lot! Due to a bit of illness on our side, the recommendation milestone has been slightly postponed, and I'm happy to say that CLARINO is definitely going to make it :-)

**Comment by bansp** [comment]
It has escaped me that one piece of information is missing from the recommendations file, namely the respStmt element that removes the warning about the recommendations not being curated.
The current display in my local instance is as follows:



<br /><br />
and I wonder if it's OK with you, @OyvindLGjesdal , if I add the following fragment to the recommendations:

```xml
      <filter>
         <centreID>CLARINO_Bergen</centreID>
      </filter>
      <respStmt>
         <name>Øyvind Gjesdal</name>
         <link>https://github.com/OyvindLGjesdal</link>
         <reviewDate>2024-06-05</reviewDate>
      </respStmt>
```
The result would then be as follows:


<br /><br />
Please kindly let me know if you are OK with that. We'd then push all the info online on Friday.

**Comment by OyvindLGjesdal** [comment]
The fragment looks good to me, thanks for adding it!

**Comment by bansp** [comment]
Thanks for the prompt response :-)

**Pull request merged**
