### PR TITLE
Update HZSK-recommendation.xml

### PR DESCRIPTION
**Pull request by lingdata-mf**
Updated link and recommendations

### CODE REVIEW

**Comment by bansp** [comment]
Thanks a lot for this update! I missed the notification. 
We're going to handle this by the end of this week.

**Comment by bansp** [comment]
And a bonus question, @lingdata-mf : can I put your name and e.g. the github handle into the "maintainer" field? That would change the classification of HZSK to "curated" and would remove some redness from the info screen, compare

https://standards.clarin.eu/sis/views/view-centre.xq?id=HZSK

https://standards.clarin.eu/sis/views/view-centre.xq?id=CLARINO_Bergen

I don't think you would be heavily taxed for time as a result ;-) 

Ah, so while I hopefully have your attention, let me ask two more questions:

1. Is it OK to include the following text, in both de and en versions, in the info field:
> Neue Datensätze (Korpora gesprochener Sprache) können auf Antrag an Prof. Dr. Kristin Bührig, Sprecherin des Hamburger Zentrums für Sprachkorpora, in die HZSK-Community innerhalb des FDRs aufgenommen werden. Voraussetzung für die Integration der Daten ins FDR ist ihre bereits vollständige Kuration.

2. Is there a chance you could link back to this SIS listing, so that I could update my centres review (#14 ) accordingly, still in time for the (postponed but coming in August) recommendations release, please?

**Comment by bansp** [comment]
I'll merge the current state just to get it into the tree, but I'll still appreciate a reply, if feasible :-)

**Comment by lingdata-mf** [comment]
Hey Piotr (@bansp), 

Sorry for the late response, but I was about to leave for vacation (and now i am).

> And a bonus question, @lingdata-mf : can I put your name and e.g. the github handle into the "maintainer" field? That would change the classification of HZSK to "curated" and would remove some redness from the info screen, compare
> 
Yeah, please do so.

> Ah, so while I hopefully have your attention, let me ask two more questions:
> 
> 1. Is it OK to include the following text, in both de and en versions, in the info field:
> 
> > Neue Datensätze (Korpora gesprochener Sprache) können auf Antrag an Prof. Dr. Kristin Bührig, Sprecherin des Hamburger Zentrums für Sprachkorpora, in die HZSK-Community innerhalb des FDRs aufgenommen werden. Voraussetzung für die Integration der Daten ins FDR ist ihre bereits vollständige Kuration.

That's fine aswell, thanks!


> 2. Is there a chance you could link back to this SIS listing, so that I could update my centres review ([Check where data-deposition centres point for format recommendations #14](https://github.com/clarin-eric/standards/issues/14) ) accordingly, still in time for the (postponed but coming in August) recommendations release, please?

If it’s not too late, we would be happy to be mentioned in it. What additional information do you need from us for this?

**Comment by bansp** [comment]
Hi Marcel! (@mflad )

Ah, you've made my day with your reply -- thanks a lot for taking time from your Urlaub! :-)

> What additional information do you need from us for this?

Just the address of the page that is linking to the SIS listing.

Coolness, I'll push the modifications before Tuesday afternoon, thanks for the green light.

Enjoy your vacation and thanks again for writing back from it! :-)

**Pull request merged**
